# -*- coding: utf-8 -*-
"""task5.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_L2DQNIj7nPK0UtaSOOKdeu4SsF3q4PC
"""

!pip install grad-cam ttach

# ==========================================
# 0. INSTALL REQUIRED LIBRARIES
# ==========================================
!pip install grad-cam ttach

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

# Select GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ==========================================
# PHASE 1: Data Preparation & Fine-Tuning
# ==========================================
# 1. Image Transformations
transform = transforms.Compose([
    transforms.Lambda(lambda x: x.convert('RGB')),
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# 2. Download and Load Caltech 101 Dataset
print("Downloading and loading Caltech 101 dataset...")
dataset = datasets.Caltech101(root='./data', download=True, transform=transform)

# Split dataset (80% Train, 20% Test)
train_size = int(len(dataset) * 0.8)
test_size = len(dataset) - train_size
train_set, test_set = torch.utils.data.random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
test_loader = DataLoader(test_set, batch_size=32, shuffle=False)

# 3. Model Fine-Tuning (ResNet-34)
print("Loading pre-trained ResNet-34 model...")
model = models.resnet34(weights=models.ResNet34_Weights.DEFAULT)

# Freeze all convolutional layers except the last block (layer4)
for param in model.parameters():
    param.requires_grad = False
for param in model.layer4.parameters():
    param.requires_grad = True

num_classes = 101
model.fc = nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.001)

# Fine-Tuning Training Loop
print("Fine-tuning original model...")
model.train()
epochs = 3
for epoch in range(epochs):
    running_loss = 0.0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}/{epochs} - Loss: {running_loss/len(train_loader):.4f}")

# ==========================================
# PHASE 2: Adversarial Attack Implementation (FGSM)
# ==========================================
def fgsm_attack(image, epsilon, data_grad):
    sign_data_grad = data_grad.sign()
    perturbed_image = image + epsilon * sign_data_grad
    return perturbed_image

# ==========================================
# PHASE 3 & 4: Explainability (Grad-CAM) & Forensic Analysis
# ==========================================
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from pytorch_grad_cam.utils.image import show_cam_on_image

target_layers = [model.layer4[-1]]
cam = GradCAM(model=model, target_layers=target_layers)

def run_forensic_analysis(image_tensor, target_label, epsilon=0.1):
    model.eval()
    img_input = image_tensor.unsqueeze(0).to(device)
    img_input.requires_grad = True

    # 1. Clean Image Prediction
    output = model(img_input)
    init_pred = output.max(1, keepdim=True)[1]

    # Calculate Gradient for FGSM Attack
    loss = criterion(output, torch.tensor([target_label]).to(device))
    model.zero_grad()
    loss.backward()
    data_grad = img_input.grad.data

    # 2. Adversarial Image Generation
    perturbed_data = fgsm_attack(img_input, epsilon, data_grad)
    output_adv = model(perturbed_data)
    adv_pred = output_adv.max(1, keepdim=True)[1]

    # 3. Grad-CAM Visualizations (With Targets specified)
    targets_clean = [ClassifierOutputTarget(init_pred.item())]
    targets_adv = [ClassifierOutputTarget(adv_pred.item())]

    grayscale_cam_clean = cam(input_tensor=img_input, targets=targets_clean)[0, :]
    grayscale_cam_adv = cam(input_tensor=perturbed_data, targets=targets_adv)[0, :]

    def deprocess_img(tensor):
        img = tensor.squeeze(0).cpu().detach().numpy().transpose(1, 2, 0)
        img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        return np.clip(img, 0, 1)

    clean_img_np = deprocess_img(img_input)
    adv_img_np = deprocess_img(perturbed_data)

    cam_clean = show_cam_on_image(clean_img_np, grayscale_cam_clean, use_rgb=True)
    cam_adv = show_cam_on_image(adv_img_np, grayscale_cam_adv, use_rgb=True)

    # Plot Visual Analysis
    fig, axes = plt.subplots(2, 2, figsize=(10, 8))
    axes[0, 0].imshow(clean_img_np)
    axes[0, 0].set_title(f"Clean Image\nPred Class: {init_pred.item()}")

    axes[0, 1].imshow(cam_clean)
    axes[0, 1].set_title("Clean Grad-CAM")

    axes[1, 0].imshow(adv_img_np)
    axes[1, 0].set_title(f"Attacked Image (eps={epsilon})\nPred Class: {adv_pred.item()}")

    axes[1, 1].imshow(cam_adv)
    axes[1, 1].set_title("Attacked Grad-CAM")

    for ax in axes.ravel():
        ax.axis('off')
    plt.tight_layout()
    plt.show()

# Run Forensic Analysis on a Sample Image
print("\n--- Running Forensic Analysis ---")
test_iter = iter(test_loader)
sample_images, sample_labels = next(test_iter)
run_forensic_analysis(sample_images[0], sample_labels[0].item(), epsilon=0.1)

# ==========================================
# PHASE 5: Model Hardening & Evaluation (The Showdown)
# ==========================================
print("\nTraining Hardened Model (Adversarial Training)...")
hardened_model = models.resnet34(weights=models.ResNet34_Weights.DEFAULT)
hardened_model.fc = nn.Linear(hardened_model.fc.in_features, num_classes)
hardened_model = hardened_model.to(device)

optimizer_h = optim.Adam(hardened_model.parameters(), lr=0.0001)

# Adversarial Training
hardened_model.train()
for epoch in range(epochs):
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        inputs.requires_grad = True

        outputs = hardened_model(inputs)
        loss = criterion(outputs, labels)
        hardened_model.zero_grad()
        loss.backward()

        adv_inputs = fgsm_attack(inputs, epsilon=0.05, data_grad=inputs.grad.data)

        optimizer_h.zero_grad()
        outputs_adv = hardened_model(adv_inputs)
        loss_adv = criterion(outputs_adv, labels)
        loss_adv.backward()
        optimizer_h.step()

# Evaluation Function for Showdown
def evaluate_model(eval_model, loader, epsilon=0.05):
    eval_model.eval()
    correct_clean = 0
    correct_adv = 0
    total = 0

    for inputs, labels in loader:
        inputs, labels = inputs.to(device), labels.to(device)

        # Test on Clean Data
        with torch.no_grad():
            outputs = eval_model(inputs)
            _, preds = torch.max(outputs, 1)
            correct_clean += (preds == labels).sum().item()

        # Test on Adversarial Data
        inputs.requires_grad = True
        outputs = eval_model(inputs)
        loss = criterion(outputs, labels)
        eval_model.zero_grad()
        loss.backward()

        adv_inputs = fgsm_attack(inputs, epsilon, inputs.grad.data)

        with torch.no_grad():
            outputs_adv = eval_model(adv_inputs)
            _, preds_adv = torch.max(outputs_adv, 1)
            correct_adv += (preds_adv == labels).sum().item()

        total += labels.size(0)

    clean_acc = (correct_clean / total) * 100
    adv_acc = (correct_adv / total) * 100
    return clean_acc, adv_acc

print("\n--- The Showdown Results ---")
orig_clean, orig_adv = evaluate_model(model, test_loader, epsilon=0.05)
hard_clean, hard_adv = evaluate_model(hardened_model, test_loader, epsilon=0.05)

print(f"Original Model  -> Clean Test Acc: {orig_clean:.2f}% | Attacked Test Acc: {orig_adv:.2f}%")
print(f"Hardened Model  -> Clean Test Acc: {hard_clean:.2f}% | Attacked Test Acc: {hard_adv:.2f}%")